### ISSUE TITLE
Autolinking doesn't work

### ISSUE THREAD

**Issue by ghost** [HorseLuvver/zim-auto-linker#1] opened 2021-09-23 16:16 UTC
Hello again,

after reading the logs, I realised that the plugin doesn't even load. Silly me just _assumed_ it loaded because the site creation worked fine. The plugin shows in the preferences, but is greyed out and "There was a problem loading this plugin" shows as description, nothing else.

Info I didn't provide on reddit:

- I'm running ArchLinux
- the plugin file is located in ~/.local/share/zim/plugins, no subfolder

Log from starting Zim the normal way
[zim.log](https://github.com/HorseLuvver/zim-auto-linker/files/7219213/zim.log)

Log from starting Zim through the terminal with debug option
[zim_debug_terminal_output.txt](https://github.com/HorseLuvver/zim-auto-linker/files/7219214/zim_debug_terminal_output.txt)

**Comment by auralluring** [comment] 2021-09-24 03:05
Oh, I didn't even think about if the folder is still the same on other distros (I use Ubuntu). If you click "open plugins folder" (on the plugins screen), does it still take you to that folder or somewhere else?

**Comment by ghost** [comment] 2021-09-24 07:31
Yes, it takes me to that folder. I have another plugin there (zim-clip) that works. The only difference is that zim-clip is in a subfolder.

**Comment by auralluring** [comment] 2021-09-24 20:01
Ok. It might be due to a syntax error, then? If you use VS Code it should tell you if something is wrong. If not, the only other thing I can think of is a dependency error (which is odd because it shouldn't have any that are not included with zim itself) Maybe send me your modified version so I can take a look at it and test it on mine.

**Comment by ghost** [comment] 2021-09-25 11:16
[autolink.zip](https://github.com/HorseLuvver/zim-auto-linker/files/7229642/autolink.zip)

Here is my Version.
As far as I can tell, there is no syntax error. I use Kate, which has syntax highlighting, but I tried with VS Code and got no error.

One thing I discovered: when I try to open other plugin files from the file manager, I get the option to run them. This does not happen with autolink.py

**Comment by auralluring** [comment] 2021-09-25 18:38
> One thing I discovered: when I try to open other plugin files from the file manager, I get the option to run them. This does not happen with autolink.py

well that is especially strange. VS Code did flag a few errors, but they were all caused by some sort of weird tab issue. So far it won't even appear in the list, but I'll keep fiddling around with it and see if I can get it to work.

**Comment by auralluring** [comment] 2021-09-25 18:54
Apparently I forgot to actually put it in the folder, smh. Once I put it in there it showed up right away, actually. Here's your version, with strange tabs removed, and some other things such as closing the files after it's done with them and some debug messages should you have issues again.
[autolink.zip](https://github.com/HorseLuvver/zim-auto-linker/files/7230225/autolink.zip)

If you still have issues after this, I think it's gotta be a dependency problem.
 

PS: I am going to try and make it into a gui instead, so this kind of thing doesn't happen so much, or at least is easier to deal with when it does.

**Comment by ghost** [comment] 2021-09-25 20:06
It works! Thanks a lot, this makes writing so much easier.

**Comment by auralluring** [comment] 2021-09-25 20:29
Oh you're welcome! It sure does :)

**Closed as completed** 2021-09-25 20:31 UTC
